### ISSUE TITLE
Order item update error

### ISSUE THREAD

**Issue by smarikachaudhary** [SwasthaniStha/Farmish#27] opened 2024-05-16 10:11 UTC
While add new item in the cart and placing order it throws an error. 
![image (1)](https://github.com/SwasthaniStha/Farmish/assets/119168456/e7979e59-ff3c-40ce-b7d1-9bd0b06498ca)

**Comment by SwasthaniStha** [comment] 2024-05-16 13:14
Error fixed! This was a value error caused by missing foreign key. When the consumer added new items to the cart, it used to throw this error. 
It was fixed by introducing a new variable in the code and passing the order items as id using foreign key which established the foreign key relationship with the order model. 

![image](https://github.com/SwasthaniStha/Farmish/assets/119651873/2e0695ad-e614-496d-87db-cd6df13dd028)

**Closed by SwasthaniStha** 2024-05-16 13:14 UTC
Labels: bug
